language: java
jdk:
- openjdk8
script: ant build
addons:
  sonarcloud:
    organization: "simozmp"
    token:
      secure: 988ca7514615f0b1a6d9250595af0b0ebe952130
script:
- ant build
- sonar-scanner
