language: java
jdk:
- openjdk8
script: ant build

language: java
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "simozmp"
    token:
      secure: "bcafaeb9cd56cac4e2c5cb4b7abfa0b1c616101a"
script:
- ant build
- sonar-scanner

